CREATE TABLE IF NOT EXISTS therapist (
	id		UUID			NOT NULL PRIMARY KEY,
	name	VARCHAR(100)	NOT NULL,
	email	VARCHAR(200)	NOT NULL
);

CREATE TABLE IF NOT EXISTS patient (
	id		UUID			NOT NULL PRIMARY KEY,
	name	VARCHAR(100)	NOT NULL,
	email	VARCHAR(200)	NOT NULL
);
